In [1]:
import sympy as sp


In [2]:
A = sp.Matrix([[0, 1, -4], [2, -3, 2], [5, -8, 7]])
A


Matrix([
[0,  1, -4],
[2, -3,  2],
[5, -8,  7]])

In [3]:
b = sp.Matrix([[8], [1], [1]])
b


Matrix([
[8],
[1],
[1]])

In [4]:
# Solve Ax = b @ SymPy
x1, x2, x3 = sp.symbols("x1 x2 x3")
sp.linsolve((A, b), x1, x2, x3)


EmptySet

In [1]:
import numpy as np


In [2]:
A = np.array([[0, 1, -4], [2, -3, 2], [5, -8, 7]])
A


array([[ 0,  1, -4],
       [ 2, -3,  2],
       [ 5, -8,  7]])

In [3]:
b = np.array([[8], [1], [1]])
b


array([[8],
       [1],
       [1]])

In [4]:
# Solve Ax = b @ NumPy
np.linalg.solve(A, b)


array([[-1.12589991e+16],
       [-9.00719925e+15],
       [-2.25179981e+15]])