In [1]:
import numpy as np


In [2]:
A = np.array([[1, -2, 1], [0, 2, -8], [-4, 5, 9]])
A


array([[ 1, -2,  1],
       [ 0,  2, -8],
       [-4,  5,  9]])

In [3]:
b = np.array([[0], [8], [-9]])
b


array([[ 0],
       [ 8],
       [-9]])

In [4]:
# Solve Ax = b @ NumPy
np.linalg.solve(A, b)


array([[29.],
       [16.],
       [ 3.]])