In [1]:
# Import SymPy package
import sympy as sp


In [2]:
# Define matrices (SymPy package)
A = sp.Matrix([[1, 1, -1]])
A


Matrix([[1, 1, -1]])

In [3]:
B = sp.Matrix([[2], [7], [8]])
B


Matrix([
[2],
[7],
[8]])

In [4]:
C = sp.Matrix([[1, 2], [3, 4]])
C


Matrix([
[1, 2],
[3, 4]])

In [5]:
D = sp.Matrix([[1, -2, 4], [5, 0, 3]])
D


Matrix([
[1, -2, 4],
[5,  0, 3]])

In [6]:
# Size of matrices
A.shape, B.shape, C.shape, D.shape


((1, 3), (3, 1), (2, 2), (2, 3))

In [7]:
# Import NumPy package
import numpy as np


In [8]:
# Define matrices (NumPy package)
A = np.array([[1, 1, -1]])
A


array([[ 1,  1, -1]])

In [9]:
B = np.array([[2], [7], [8]])
B


array([[2],
       [7],
       [8]])

In [10]:
C = np.array([[1, 2], [3, 4]])
C


array([[1, 2],
       [3, 4]])

In [11]:
D = np.array([[1, -2, 4], [5, 0, 3]])
D


array([[ 1, -2,  4],
       [ 5,  0,  3]])

In [12]:
# Size of matrices
A.shape, B.shape, C.shape, D.shape


((1, 3), (3, 1), (2, 2), (2, 3))