In [1]:
import sympy as sp
import numpy as np


In [2]:
# Example 3.1
A = sp.Matrix([[2, 3], [3, -6]])
A


Matrix([
[2,  3],
[3, -6]])

In [3]:
# Characteristic polynomial
A.charpoly()


PurePoly(lambda**2 + 4*lambda - 21, lambda, domain='ZZ')

In [4]:
# Factorize the polynomial
sp.factor(A.charpoly().as_expr())


(lambda - 3)*(lambda + 7)

In [5]:
# Eigenvalues of A
A.eigenvals()


{3: 1, -7: 1}

In [6]:
# Eigenvalues and eigenvectors of A
A.eigenvects()


[(-7,
  1,
  [Matrix([
   [-1/3],
   [   1]])]),
 (3,
  1,
  [Matrix([
   [3],
   [1]])])]

In [7]:
# Example 3.2
B = sp.Matrix([[4, -1, 6], [2, 1, 6], [2, -1, 8]])
B


Matrix([
[4, -1, 6],
[2,  1, 6],
[2, -1, 8]])

In [8]:
# Eigenvalues and eigenvectors of B
B.eigenvects()


[(2,
  2,
  [Matrix([
   [1/2],
   [  1],
   [  0]]),
   Matrix([
   [-3],
   [ 0],
   [ 1]])]),
 (9,
  1,
  [Matrix([
   [1],
   [1],
   [1]])])]

In [9]:
# Example 3.3
C = sp.Matrix([[4, 0, -1, -2], [-1, 3, 0, 1], [0, 0, 4, 0], [1, 1, -1, 1]])
C


Matrix([
[ 4, 0, -1, -2],
[-1, 3,  0,  1],
[ 0, 0,  4,  0],
[ 1, 1, -1,  1]])

In [10]:
# Eigenvalues and eigenvectors of C
C.eigenvects()


[(2,
  2,
  [Matrix([
   [1],
   [0],
   [0],
   [1]])]),
 (4,
  2,
  [Matrix([
   [-1],
   [ 1],
   [ 0],
   [ 0]]),
   Matrix([
   [ 1],
   [ 0],
   [-2],
   [ 1]])])]

In [11]:
# Example 3.4
D = sp.Matrix([[3, 1, -1], [0, 2, 1], [0, -1, 2]])
D


Matrix([
[3,  1, -1],
[0,  2,  1],
[0, -1,  2]])

In [12]:
# Eigenvalues and eigenvectors of D
D.eigenvects()


[(3,
  1,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (2 - I,
  1,
  [Matrix([
   [-I],
   [ I],
   [ 1]])]),
 (2 + I,
  1,
  [Matrix([
   [ I],
   [-I],
   [ 1]])])]

In [13]:
# Example 3.2
B = np.array([[4, -1, 6], [2, 1, 6], [2, -1, 8]])
B


array([[ 4, -1,  6],
       [ 2,  1,  6],
       [ 2, -1,  8]])

In [14]:
# Eigenvalues and eigenvectors of B @ NumPy
np.linalg.eig(B)


(array([9.+0.00000000e+00j, 2.+3.14018492e-16j, 2.-3.14018492e-16j]),
 array([[ 0.57735027+0.j        , -0.29157823-0.33778223j,
         -0.29157823+0.33778223j],
        [ 0.57735027+0.j        , -0.88637126+0.j        ,
         -0.88637126-0.j        ],
        [ 0.57735027+0.j        , -0.0505358 +0.11259408j,
         -0.0505358 -0.11259408j]]))

In [15]:
# A 10x10 random matrix
R = np.random.randint(0, 4, size=(10, 10))
R = R + R.T
R


array([[0, 3, 4, 3, 2, 2, 4, 3, 4, 6],
       [3, 0, 3, 3, 4, 4, 2, 1, 5, 1],
       [4, 3, 4, 3, 3, 3, 0, 2, 3, 3],
       [3, 3, 3, 0, 6, 1, 2, 0, 0, 1],
       [2, 4, 3, 6, 4, 3, 3, 4, 0, 2],
       [2, 4, 3, 1, 3, 2, 2, 6, 6, 2],
       [4, 2, 0, 2, 3, 2, 4, 2, 3, 3],
       [3, 1, 2, 0, 4, 6, 2, 6, 4, 0],
       [4, 5, 3, 0, 0, 6, 3, 4, 4, 2],
       [6, 1, 3, 1, 2, 2, 3, 0, 2, 2]])

In [16]:
# Eigenvalues and eigenvectors of R @ NumPy
np.linalg.eig(R)


(array([27.77358964,  8.14270447,  5.96798917,  4.20800259,  1.9297148 ,
        -7.36153451, -5.20049538, -4.6394623 , -1.74111339, -3.07939507]),
 array([[-0.33811335, -0.14348379,  0.3117255 , -0.04088229, -0.23852243,
          0.63013077,  0.24256452, -0.14233263,  0.03452777,  0.48166544],
        [-0.30364803, -0.05050812, -0.01054428,  0.15816101,  0.51417916,
         -0.26638612,  0.6488831 ,  0.2848479 , -0.12816571,  0.16175567],
        [-0.31865391, -0.17243354,  0.05146441,  0.63546346, -0.24433455,
         -0.03696557, -0.00173842,  0.1144517 ,  0.52824727, -0.33022832],
        [-0.21880342, -0.4403175 , -0.22901572,  0.04350682,  0.17734415,
         -0.33799099, -0.20710237, -0.64458235,  0.08231328,  0.3050613 ],
        [-0.33595126, -0.38359351, -0.53868002, -0.115432  ,  0.04491977,
          0.30361697, -0.29371941,  0.43159509, -0.24715591, -0.09305668],
        [-0.36558597,  0.3358618 , -0.09831167,  0.07723134,  0.11122016,
          0.24014537,  0.12669808

In [17]:
# Same matrix in SymPy
S = sp.Matrix(R)
S


Matrix([
[0, 3, 4, 3, 2, 2, 4, 3, 4, 6],
[3, 0, 3, 3, 4, 4, 2, 1, 5, 1],
[4, 3, 4, 3, 3, 3, 0, 2, 3, 3],
[3, 3, 3, 0, 6, 1, 2, 0, 0, 1],
[2, 4, 3, 6, 4, 3, 3, 4, 0, 2],
[2, 4, 3, 1, 3, 2, 2, 6, 6, 2],
[4, 2, 0, 2, 3, 2, 4, 2, 3, 3],
[3, 1, 2, 0, 4, 6, 2, 6, 4, 0],
[4, 5, 3, 0, 0, 6, 3, 4, 4, 2],
[6, 1, 3, 1, 2, 2, 3, 0, 2, 2]])

In [18]:
# Eigenvalues and eigenvectors of R @ SymPy
S.eigenvects()


[(CRootOf(_lambda**10 - 26*_lambda**9 - 167*_lambda**8 + 3006*_lambda**7 + 11615*_lambda**6 - 107978*_lambda**5 - 355718*_lambda**4 + 1331564*_lambda**3 + 4053196*_lambda**2 - 3762790*_lambda - 10436888, 0),
  1,
  [Matrix([
   [    -10139424854562267605886405952*CRootOf(_lambda**10 - 26*_lambda**9 - 167*_lambda**8 + 3006*_lambda**7 + 11615*_lambda**6 - 107978*_lambda**5 - 355718*_lambda**4 + 1331564*_lambda**3 + 4053196*_lambda**2 - 3762790*_lambda - 10436888, 0)**6/1440391758938171504046744773137 + 4359988385244361250467489241*CRootOf(_lambda**10 - 26*_lambda**9 - 167*_lambda**8 + 3006*_lambda**7 + 11615*_lambda**6 - 107978*_lambda**5 - 355718*_lambda**4 + 1331564*_lambda**3 + 4053196*_lambda**2 - 3762790*_lambda - 10436888, 0)**7/31688618696639773089028385009014 - 43797556063741250911769243275682*CRootOf(_lambda**10 - 26*_lambda**9 - 167*_lambda**8 + 3006*_lambda**7 + 11615*_lambda**6 - 107978*_lambda**5 - 355718*_lambda**4 + 1331564*_lambda**3 + 4053196*_lambda**2 - 3762790*_lambda