In [1]:
import sympy as sp
import numpy as np


In [2]:
# Example 3.9
A = np.array([[1, 3, 3], [-3, -5, -3], [3, 3, 1]])
A


array([[ 1,  3,  3],
       [-3, -5, -3],
       [ 3,  3,  1]])

In [3]:
I = np.eye(3)
I


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# (A+5I)^2 - (A-I)^2
np.linalg.matrix_power(A + 5 * I, 2) - np.linalg.matrix_power(A - I, 2)


array([[ 36.,  36.,  36.],
       [-36., -36., -36.],
       [ 36.,  36.,  36.]])

In [5]:
# (A+5I)^20 - (A-I)^20
np.linalg.matrix_power(A + 5 * I, 20) - np.linalg.matrix_power(A - I, 20)


array([[ 3.65615844e+15,  3.65615844e+15,  3.65615844e+15],
       [-3.65615844e+15, -3.65615844e+15, -3.65615844e+15],
       [ 3.65615844e+15,  3.65615844e+15,  3.65615844e+15]])

In [6]:
# (A+5I)^3724 - (A-I)^3724
np.linalg.matrix_power(A + 5 * I, 3724) - np.linalg.matrix_power(A - I, 3724)


d:\Program Files\Python310\lib\site-packages\numpy\linalg\linalg.py:654: RuntimeWarning: overflow encountered in matmul
  z = a if z is None else fmatmul(z, z)
d:\Program Files\Python310\lib\site-packages\numpy\linalg\linalg.py:657: RuntimeWarning: invalid value encountered in matmul
  result = z if result is None else fmatmul(result, z)
d:\Program Files\Python310\lib\site-packages\numpy\linalg\linalg.py:654: RuntimeWarning: invalid value encountered in matmul
  z = a if z is None else fmatmul(z, z)
d:\Program Files\Python310\lib\site-packages\numpy\linalg\linalg.py:657: RuntimeWarning: overflow encountered in matmul
  result = z if result is None else fmatmul(result, z)


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])