In [1]:
import numpy as np

A = np.array([[6, 3, 2, 5], [3, 8, 5, 6], [2, 5, 4, 5], [5, 6, 5, 2]])
A


array([[6, 3, 2, 5],
       [3, 8, 5, 6],
       [2, 5, 4, 5],
       [5, 6, 5, 2]])

In [2]:
np.linalg.eig(A)


(array([18.37878448,  4.2761543 , -3.37813216,  0.72319338]),
 array([[-0.42046042, -0.84845279,  0.31313495, -0.07271451],
        [-0.6197679 ,  0.43924433,  0.21547076, -0.61361593],
        [-0.44479769,  0.28301455,  0.34945395,  0.77455775],
        [-0.49117796, -0.08423208, -0.85638822,  0.13508654]]))

In [3]:
B = A[0:3, 0:3]
B


array([[6, 3, 2],
       [3, 8, 5],
       [2, 5, 4]])

In [4]:
np.linalg.eig(B)


(array([13.19251931,  4.19280421,  0.61467648]),
 array([[ 0.44813055,  0.89394688,  0.00616301],
        [ 0.74077971, -0.36747195, -0.56232535],
        [ 0.50042426, -0.2565606 ,  0.82689311]]))

In [5]:
C = A[1:4, 1:4]
C


array([[8, 5, 6],
       [5, 4, 5],
       [6, 5, 2]])

In [6]:
np.linalg.eig(C)


(array([15.78059973,  0.75095036, -2.53155008]),
 array([[-0.70641567, -0.65152327, -0.27657607],
        [-0.50869908,  0.73903826, -0.44164204],
        [-0.49214037,  0.17128887,  0.8534975 ]]))