In [1]:
import sympy as sp
import numpy as np


In [2]:
A = sp.Matrix([[4, 11, 14], [8, 7, -2]])
A


Matrix([
[4, 11, 14],
[8,  7, -2]])

In [3]:
# Singular Values
A.singular_values()


[6*sqrt(10), 3*sqrt(10), 0]

In [4]:
# Singular Value Decomposition @ SymPy
U, S, V = A.singular_value_decomposition()


In [5]:
U


Matrix([
[ -sqrt(10)/10, 3*sqrt(10)/10],
[3*sqrt(10)/10,   sqrt(10)/10]])

In [6]:
S


Matrix([
[3*sqrt(10),          0],
[         0, 6*sqrt(10)]])

In [7]:
V


Matrix([
[ 2/3, 1/3],
[ 1/3, 2/3],
[-2/3, 2/3]])

In [8]:
B = A.T
B


Matrix([
[ 4,  8],
[11,  7],
[14, -2]])

In [9]:
U, S, V = B.singular_value_decomposition()
U


Matrix([
[ 2/3, 1/3],
[ 1/3, 2/3],
[-2/3, 2/3]])

In [10]:
S


Matrix([
[3*sqrt(10),          0],
[         0, 6*sqrt(10)]])

In [11]:
V


Matrix([
[ -sqrt(10)/10, 3*sqrt(10)/10],
[3*sqrt(10)/10,   sqrt(10)/10]])

In [12]:
A = np.array([[4, 11, 14], [8, 7, -2]])
A


array([[ 4, 11, 14],
       [ 8,  7, -2]])

In [13]:
# Singular Value Decomposition @ NumPy
np.linalg.svd(A)


(array([[-0.9486833 , -0.31622777],
        [-0.31622777,  0.9486833 ]]),
 array([18.97366596,  9.48683298]),
 array([[-0.33333333, -0.66666667, -0.66666667],
        [ 0.66666667,  0.33333333, -0.66666667],
        [-0.66666667,  0.66666667, -0.33333333]]))

In [14]:
B = A.T
B


array([[ 4,  8],
       [11,  7],
       [14, -2]])

In [15]:
np.linalg.svd(B)


(array([[-0.33333333, -0.66666667, -0.66666667],
        [-0.66666667, -0.33333333,  0.66666667],
        [-0.66666667,  0.66666667, -0.33333333]]),
 array([18.97366596,  9.48683298]),
 array([[-0.9486833 , -0.31622777],
        [ 0.31622777, -0.9486833 ]]))