In [1]:
import sympy as sp
import numpy as np


In [2]:
A = sp.Matrix([[6, -2, -1], [-2, 6, -1], [-1, -1, 5]])
A


Matrix([
[ 6, -2, -1],
[-2,  6, -1],
[-1, -1,  5]])

In [3]:
A.eigenvects()


[(3,
  1,
  [Matrix([
   [1],
   [1],
   [1]])]),
 (6,
  1,
  [Matrix([
   [-1/2],
   [-1/2],
   [   1]])]),
 (8,
  1,
  [Matrix([
   [-1],
   [ 1],
   [ 0]])])]

In [4]:
A = np.array([[6, -2, -1], [-2, 6, -1], [-1, -1, 5]])
A


array([[ 6, -2, -1],
       [-2,  6, -1],
       [-1, -1,  5]])

In [5]:
np.linalg.eig(A)


(array([3., 8., 6.]),
 array([[ 5.77350269e-01,  7.07106781e-01, -4.08248290e-01],
        [ 5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
        [ 5.77350269e-01, -2.79509395e-16,  8.16496581e-01]]))

In [6]:
A = sp.Matrix([[3, -2, 4], [-2, 6, 2], [4, 2, 3]])
A


Matrix([
[ 3, -2, 4],
[-2,  6, 2],
[ 4,  2, 3]])

In [7]:
A.eigenvects()


[(-2,
  1,
  [Matrix([
   [  -1],
   [-1/2],
   [   1]])]),
 (7,
  2,
  [Matrix([
   [-1/2],
   [   1],
   [   0]]),
   Matrix([
   [1],
   [0],
   [1]])])]

In [8]:
P, D = A.diagonalize()
P, D


(Matrix([
 [-2, -1, 1],
 [-1,  2, 0],
 [ 2,  0, 1]]),
 Matrix([
 [-2, 0, 0],
 [ 0, 7, 0],
 [ 0, 0, 7]]))

In [9]:
P


Matrix([
[-2, -1, 1],
[-1,  2, 0],
[ 2,  0, 1]])

In [10]:
P.QRdecomposition()


(Matrix([
 [-2/3,  -sqrt(5)/5, 4*sqrt(5)/15],
 [-1/3, 2*sqrt(5)/5, 2*sqrt(5)/15],
 [ 2/3,           0,    sqrt(5)/3]]),
 Matrix([
 [3,       0,           0],
 [0, sqrt(5),  -sqrt(5)/5],
 [0,       0, 3*sqrt(5)/5]]))

In [11]:
A = sp.Matrix([[3, 2, 2, 2], [2, 3, 2, 2], [2, 2, 3, 2], [2, 2, 2, 3]])
A


Matrix([
[3, 2, 2, 2],
[2, 3, 2, 2],
[2, 2, 3, 2],
[2, 2, 2, 3]])

In [12]:
P, D = A.diagonalize()
P, D


(Matrix([
 [-1, -1, -1, 1],
 [ 1,  0,  0, 1],
 [ 0,  1,  0, 1],
 [ 0,  0,  1, 1]]),
 Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 9]]))

In [13]:
Q, R = P.QRdecomposition()
Q


Matrix([
[-sqrt(2)/2, -sqrt(6)/6, -sqrt(3)/6, 1/2],
[ sqrt(2)/2, -sqrt(6)/6, -sqrt(3)/6, 1/2],
[         0,  sqrt(6)/3, -sqrt(3)/6, 1/2],
[         0,          0,  sqrt(3)/2, 1/2]])