In [1]:
import sympy as sp
import numpy as np


In [2]:
A = sp.Matrix([[1, 0, 0], [1, 1, 0], [1, 1, 1], [1, 1, 1]])
A


Matrix([
[1, 0, 0],
[1, 1, 0],
[1, 1, 1],
[1, 1, 1]])

In [3]:
# QR decomposition @ SymPy
Q, R = A.QRdecomposition()
display(Q, R)


Matrix([
[1/2, -sqrt(3)/2,          0],
[1/2,  sqrt(3)/6, -sqrt(6)/3],
[1/2,  sqrt(3)/6,  sqrt(6)/6],
[1/2,  sqrt(3)/6,  sqrt(6)/6]])

Matrix([
[2,       3/2,         1],
[0, sqrt(3)/2, sqrt(3)/3],
[0,         0, sqrt(6)/3]])

In [4]:
Q @ R


Matrix([
[1, 0, 0],
[1, 1, 0],
[1, 1, 1],
[1, 1, 1]])

In [5]:
Q.T @ Q


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [6]:
A = np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1], [1, 1, 1]])
A


array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
# QR decomposition @ NumPy
Q, R = np.linalg.qr(A)
display(Q, R)


array([[-0.5       ,  0.8660254 ,  0.        ],
       [-0.5       , -0.28867513,  0.81649658],
       [-0.5       , -0.28867513, -0.40824829],
       [-0.5       , -0.28867513, -0.40824829]])

array([[-2.        , -1.5       , -1.        ],
       [ 0.        , -0.8660254 , -0.57735027],
       [ 0.        ,  0.        , -0.81649658]])

In [8]:
Q @ R


array([[ 1.00000000e+00,  8.69063787e-17, -1.34358683e-16],
       [ 1.00000000e+00,  1.00000000e+00,  1.61842956e-16],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [9]:
Q.T @ Q


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 6.34802232e-18],
       [0.00000000e+00, 6.34802232e-18, 1.00000000e+00]])

In [10]:
# QR decomposition (complete form) @ NumPy
Q, R = np.linalg.qr(A, mode="complete")
display(Q, R)


array([[-5.00000000e-01,  8.66025404e-01,  0.00000000e+00,
         0.00000000e+00],
       [-5.00000000e-01, -2.88675135e-01,  8.16496581e-01,
        -6.99362418e-17],
       [-5.00000000e-01, -2.88675135e-01, -4.08248290e-01,
        -7.07106781e-01],
       [-5.00000000e-01, -2.88675135e-01, -4.08248290e-01,
         7.07106781e-01]])

array([[-2.        , -1.5       , -1.        ],
       [ 0.        , -0.8660254 , -0.57735027],
       [ 0.        ,  0.        , -0.81649658],
       [ 0.        ,  0.        ,  0.        ]])