In [1]:
import numpy as np


In [2]:
A = np.array([[1, 1, -1]])
A


array([[ 1,  1, -1]])

In [3]:
B = np.array([[2], [7], [8]])
B


array([[2],
       [7],
       [8]])

In [4]:
C = np.array([[1, 2], [3, 4]])
C


array([[1, 2],
       [3, 4]])

In [5]:
D = np.array([[1, -2, 4], [5, 0, 3]])
D


array([[ 1, -2,  4],
       [ 5,  0,  3]])